### ISSUE TITLE
运行报错 panic: mismatching message name: got datahubProtos.StringPair, want pbmodel.StringPair

### ISSUE THREAD

**Issue by yesgs** [aliyun/aliyun-datahub-sdk-go#7]
```
panic: mismatching message name: got datahubProtos.StringPair, want pbmodel.StringPair

goroutine 1 [running]:
google.golang.org/protobuf/internal/impl.legacyLoadMessageDesc(0xb4aac0, 0xa29780, 0xa66f0e, 0x12, 0x0, 0x0)
	/home/king/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/legacy_message.go:136 +0x882
google.golang.org/protobuf/internal/impl.legacyLoadMessageInfo(0xb4aac0, 0xa29780, 0xa66f0e, 0x12, 0x0)
	/home/king/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/legacy_message.go:48 +0xbd
google.golang.org/protobuf/internal/impl.Export.LegacyMessageTypeOf(0xb3bd60, 0x0, 0xa66f0e, 0x12, 0xc000159e88, 0x44db1c)
	/home/king/go/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/legacy_export.go:35 +0xa5
github.com/golang/protobuf/proto.RegisterType(0xb3bd60, 0x0, 0xa66f0e, 0x12)
	/home/king/go/pkg/mod/github.com/golang/protobuf@v1.4.0/proto/registry.go:186 +0x4d
github.com/aliyun/aliyun-datahub-sdk-go/datahub/pbmodel.init.0()
	/home/king/go/pkg/mod/github.com/aliyun/aliyun-datahub-sdk-go@v0.0.0-20200407024403-e33d422bfb50/datahub/pbmodel/datahub.pb.go:544 +0x4f
```

操作系统: ubuntu
go version: 14

**Comment by yqfclid** [comment]
+1 我快吐了 这个有解决办法吗

**Comment by beJuvenile** [comment]
@yqfclid 请问，解决了吗？我也遇到这个问题了

**Comment by linus-lc** [comment]
protobuf 1.4.0有个改动导致的，目前先把protobuf降到1.3.5吧。

**Comment by beJuvenile** [comment]
protobuf使用1.3.5版本就行了

**Comment by wsqwsq-98** [comment]
如何使用dep ensure降低protobuf版本呀？
[[override]]
  version = "1.3.5"
  name = "github.com/golang/protobuf"
不起作用

**Comment by RitaCaoCN** [comment]
replace github.com/golang/protobuf v1.4.x => github.com/golang/protobuf v1.3.5
